spring.application.name=ride-service

server.port=${PORT:8077}

#spring.datasource.url=jdbc:postgresql://dpg-d3ucd8bipnbc738rut5g-a.oregon-postgres.render.com/gorap
#spring.datasource.username=gorap
#spring.datasource.password=LBtQuhpND1NRxcBWdK530TXmgCAeI4po

spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

server.servlet.context-path=/gorap


app.jwtSecret=ThisIsA256BitSecretKeyForJWT1234567890 
app.jwtExpirationMs=86400000

            
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=app.ridz@gmail.com
spring.mail.password=bdsi kvyq gnht kgmt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
from.email.address=app.ridz@gmail.com




# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
