spring.application.name=ride-service

server.port=8077

spring.datasource.url=jdbc:postgresql://localhost:5432/gorap
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
server.servlet.context-path=/gorap


app.jwtSecret=ThisIsA256BitSecretKeyForJWT1234567890 
app.jwtExpirationMs=86400000           



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=app.ridz@gmail.com
spring.mail.password=bdsi kvyq gnht kgmt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
from.email.address=app.ridz@gmail.com


# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
