spring.application.name=ride-service

server.port=${PORT:8077}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
server.servlet.context-path=/gorap


app.jwtSecret=ThisIsA256BitSecretKeyForJWT1234567890 
app.jwtExpirationMs=86400000
profile.name=prod            


# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
